name: Release

on:
  workflow_dispatch: {}
  

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 19.x
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - name: Publish to NPM
        run: node ./scripts/publish.js
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}