name: Test
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
    paths-ignore:
      - "**/*.md"
  workflow_dispatch: {} # allow manual triggering just in case
concurrency: ${{ github.workflow }}-${{ github.head_ref }}
env:
  GIT_REF: ${{ github.head_ref || github.ref }}
  GIT_REPO: ${{ github.repository }}
permissions:
  contents: read
jobs:
  prebuild:
    uses: ./.github/workflows/prebuild.yml
    with:
      # Sadly, we cannot use environment variables here
      ref: ${{ github.head_ref || github.ref }}
      repository: ${{ github.repository }}
      node_version: 22.x
  test:
    needs: [prebuild]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ env.GIT_REF }}
          repository: ${{ env.GIT_REPO }}
      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 22.x
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          path: prebuilds
          merge-multiple: true
      - run: tree prebuilds
      - run: yarn install --ignore-scripts --ignore-engines
      - run: yarn build
      - run: yarn
      - run: yarn test
